### PR TITLE
Cleanup repository

### LINKED ISSUE #32: duplicate functions and deprecated code hinder code unity
multiple versions of the same function and code clutter should be removed

### LINKED ISSUE #38: interrupted migration file does not distinguish between different blocks
add block number to the name interrupted-migration.json file

encode block number into the name of the file.

change name interrupted-migration.json to migration-state.json

### PR DESCRIPTION
**Pull request by thecodingshrimp**
see issue #32

### CODE REVIEW

**Comment by thecodingshrimp** [comment]
there are so many commits related to this branch because I merged it already with continue_migration. We would've had to do it either way, this way you can probably just merge it after #34 is merged

**Comment by thecodingshrimp** [comment]
added commit to fix #38

**Comment by thecodingshrimp** [comment]
we can now also use the latest version of truffle again.

**Review by informartin — APPROVED** [review]
Looking good to me, thank you!

**Pull request merged**
